SELECT
  A.PRODUCT_CODE,
  sum(A.PRICE*B.SALES_AMOUNT) as SALES
FROM
  PRODUCT as A
JOIN
  OFFLINE_SALE as B
  ON A.PRODUCT_ID=B.PRODUCT_ID
GROUP BY
  PRODUCT_CODE
ORDER BY
  SALES DESC,
  PRODUCT_CODE; 