SELECT
  a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM
  REST_INFO as a
JOIN
  (SELECT
     FOOD_TYPE,max(FAVORITES) as max_v
   FROM REST_INFO
  GROUP BY FOOD_TYPE) as b
ON a.FOOD_TYPE = b.FOOD_TYPE AND a.FAVORITES = b.max_v
ORDER BY FOOD_TYPE DESC;

  