SELECT 
  A.ITEM_ID,
  A.ITEM_NAME,
  A.RARITY
FROM ITEM_INFO as A
JOIN
  ITEM_TREE as B
  ON A.ITEM_ID=B.ITEM_ID
JOIN
  ITEM_INFO as C
  ON B.PARENT_ITEM_ID=C.ITEM_ID
-- WHERE B.PARENT_ITEM_ID IS NOT NULL AND C.RARITY='RARE'
WHERE C.RARITY='RARE' 
ORDER BY A.ITEM_ID desc;
