SELECT
  YEAR(A.DIFFERENTIATION_DATE) as 'YEAR',
  B.D-A.SIZE_OF_COLONY as 'YEAR_DEV',
  A.ID FROM ECOLI_DATA as A 
JOIN 
  (SELECT 
     YEAR(DIFFERENTIATION_DATE) as 'YEAR',
     MAX(SIZE_OF_COLONY) as D 
   FROM ECOLI_DATA 
   GROUP BY YEAR(DIFFERENTIATION_DATE)) as B
ON YEAR(A.DIFFERENTIATION_DATE)=B.YEAR
ORDER BY YEAR,YEAR_DEV;