SELECT 
  SUM(C.SCORE) AS SCORE,
  C.EMP_NO,
  B.EMP_NAME,
  B.POSITION,
  B.EMAIL
FROM 
  HR_DEPARTMENT as A 
JOIN 
  HR_EMPLOYEES as B ON A.DEPT_ID=B.DEPT_ID
JOIN 
  HR_GRADE  as C ON B.EMP_NO=C.EMP_NO
WHERE
  C.YEAR=2022
GROUP BY
  C.EMP_NO
ORDER BY 
  SCORE DESC
LIMIT 1;